# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-09-13 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=11)),
                ('status', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Servidores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('puerto', models.CharField(max_length=11)),
                ('servicio', models.CharField(max_length=8)),
                ('cliente', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=8)),
            ],
        ),
    ]
